dist: dex

env:
  global:
    - REGISTRY_NAME=1049651653
    - REGISTRY_PWD=lmg7831336
    - REGISTRY=docker.io/1049651653
    - IMAGE_NAME=dex:v2.9.0
    - CODE_TAG=v2.9.x
    
arch:
#  - amd64
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/dexidp/dex.git

script:
  - cd dex
  - docker build -t ${REGISTRY}/${IMAGE_NAME} -f Dockerfile .
  
after_success:
- docker login -u ${REGISTRY_NAME} -p ${REGISTRY_PWD} ${REGISTRY}
- docker push ${REGISTRY}/${IMAGE_NAME}
