dist: dex

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - IMAGE_NAME=pkskubeflow/dex:v2.13.0
    - CODE_TAG=v2.13.x

    
arch:
#  - amd64
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/dexidp/dex.git

script:
  - cd dex
  - docker build -t ${IMAGE_NAME} -f Dockerfile .
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${IMAGE_NAME}
